language: csharp
solution: NoStringEvaluating.sln
mono: none
dist: xenial
os: linux
dotnet: 6.0
install:
 - dotnet restore
script:
 - dotnet build --configuration Release
 - dotnet test NoStringEvaluating.Tests/NoStringEvaluating.Tests.csproj
 - |
   if [ $TRAVIS_BRANCH == "master" ]; then
     dotnet nuget push NoStringEvaluating/bin/Release/*.nupkg -s "https://nuget.org" -k $EVALUATOR_NUGET_API_KEY --skip-duplicate
     dotnet nuget push NoStringEvaluating.Extensions.Microsoft.DependencyInjection/bin/Release/*.nupkg -s "https://nuget.org" -k $MICROSOFT_DI_NUGET_API_KEY --skip-duplicate
   fi